### ISSUE TITLE
Ride the elevator

### ISSUE THREAD

**Issue by murchandamus** [AlSzacrel/mindstorms#12]
After crossing the bridge, Marva will need to conquer the elevator.

Implement handling of Sensor Light Plate, Bluetooth Communication with Elevator, driving onto elevator plate, waiting, leaving the elevator.

**Comment by briemla** [comment]
Steps:
1. Drive on the light sensor plate and stop. 
2. Try to establish a Bluetooth connection to the elevator. 
3. If the connection could be established, the elevator will switch the light sensor plate to green. 
4. Drive straight into the elevator. 
5. Tell the elevator to go down.
6. Ask the elevator if it is down
7. Drive out of the elevator

**It is only allowed to drive into the elevator when the Bluetooth connection could be established and the light plate is green. Otherwise Marva could be damaged.**
